---
- name: Deploy Podman network quadlet file - {{ network.name }}
  ansible.builtin.template:
    src: network.j2
    dest: "{{ podman_quadlet_dir }}/{{ network.name }}.network"
    mode: "0644"
    owner: "{{ (podman_quadlet_scope == 'user') | ternary(podman_quadlet_user, 'root') }}"
    group: "{{ (podman_quadlet_scope == 'user') | ternary(podman_quadlet_user, 'root') }}"
  become: "{{ podman_quadlet_scope == 'system' }}"
  when: network.state | default(podman_quadlet_state) == 'present'
  notify: reload systemd

- name: Remove Podman network quadlet file - {{ network.name }}
  ansible.builtin.file:
    path: "{{ podman_quadlet_dir }}/{{ network.name }}.network"
    state: absent
  become: "{{ podman_quadlet_scope == 'system' }}"
  when: network.state | default(podman_quadlet_state) == 'absent'
  notify: reload systemd

- name: Enable and start network service - {{ network.name }}
  ansible.builtin.systemd:
    name: "{{ network.name }}-network"
    enabled: "{{ network.enabled | default(podman_quadlet_enable_services) }}"
    state: "{{ (network.started | default(podman_quadlet_start_services)) | ternary('started', omit) }}"
    scope: "{{ podman_quadlet_systemd_scope }}"
  become: "{{ podman_quadlet_scope == 'system' }}"
  become_user: "{{ (podman_quadlet_scope == 'user') | ternary(podman_quadlet_user, omit) }}"
  when:
    - network.state | default(podman_quadlet_state) == 'present'
    - podman_quadlet_reload_daemon
