galaxy_info:
  author: Devin Parrish
  description: Installs and configures Microshift
  company: Red Hat

  license: GPL-2.0-or-later

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 8

  galaxy_tags:
    - system
    - linux
    - containers
    - kubernetes

dependencies: []