---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"]

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.ip_forward
    value: "1"
    state: present
    reload: true
  when: ansible_all_ipv6_addresses

- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: 0600
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"]

- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"]

- name: Set bridge-nf-call-iptables
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"]
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Add /usr/local/bin to sudo secure_path
  ansible.builtin.lineinfile:
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: 'visudo -cf %s'
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"]
