---
- name: Check for raspberrypi in /proc/cpuinfo
  ansible.builtin.command:
    cmd: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
  register: grep_cpuinfo_raspberrypi
  failed_when: false
  changed_when: false

- name: Check for raspberrypi in /proc/device-tree/model
  ansible.builtin.command:
    cmd: grep -E "Raspberry Pi" /proc/device-tree/model
  register: grep_device_tree_model_raspberrypi
  failed_when: false
  changed_when: false

- name: Set raspberry_pi fact to true
  ansible.builtin.set_fact:
    raspberry_pi: true
  when:
    - grep_cpuinfo_raspberrypi.rc == 0 or grep_device_tree_model_raspberrypi.rc == 0

- name: Set detected_distribution to Raspbian
  ansible.builtin.set_fact:
    detected_distribution: Raspbian
  when: >
    - raspberry_pi | default(false)
    - ansible_facts.lsb.id | default("") == Raspbian or
      ansible_facts.lsb.description | default("") is match("[Rr]aspbian.*")

- name: Set detected_distribution to Raspbian (arm64 or Debian Buster)
  ansible.builtin.set_fact:
    detected_distribution: Raspbian
  when:
    - ansible_facts.architecture is search("aarch64")
    - raspberry_pi | default(false)
    - ansible_facts.lsb.description | default("") is match("Debian.*buster")

- name: Set detected_distribution_major_version
  ansible.builtin.set_fact:
    detected_distribution_major_version: "{{ ansible_facts.lsb.major_release }}"
  when:
    - detected_distribution | default("") == "Raspbian"

- name: Execute OS related tasks on Raspberry Pi devices
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - supported_oses/{{ detected_distribution }}-{{ detected_distribution_major_version }}.yml
    - supported_oses/{{ detected_distribution }}.yml
    - supported_oses/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml
    - supported_oses/{{ ansible_distribution }}.yml
    - supported_oses/default.yml
  when:
    - raspberry_pi | default(false)
