---
- name: '[CENTOS] Enable CRI-O module'
  ansible.builtin.dnf:
    name: 'cri-o:1.2.1'
    state: present

- name: '[CENTOS] Install CRI-O'
  ansible.builtin.dnf:
    name:
      - cri-o
      - cri-tools

- name: '[CENTOS] Enable CRI-O at boot'
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: true