---
- name: '[CENTOS] Install container tools'
  ansible.builtin.dnf:
    name: '@container-tools'
    state: present

- name: '[CENTOS] Enable CRI-O at boot'
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: true