---
- name: '[CENTOS] Enable CRI-O module'
  ansible.builtin.dnf:
    name: '@cri-o:1.21'
    state: present
    update_cache: true

- name: '[CENTOS] Install CRI-O'
  ansible.builtin.dnf:
    name:
      - cri-o
      - cri-tools

- name: '[CENTOS] Enable CRI-O at boot'
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: true

- name: '[CENTOS] Enable Microshift repository'
  community.general.copr:
    name: '@redhat-et/microshift'
    state: enabled

- name: '[CENTOS] Install Microshift'
  ansible.builtin.dnf:
    name: microshift
    state: present

- name: '[CENTOS] Start and Enable Microshift'
  ansible.builtin.systemd:
    name: microshift
    state: started
    enabled: true