- name: Ensure Nginx chart is installed
  hosts: all
  become: true
  gather_facts: false
  vars:
    helm_install_repo_name: bitnami
    helm_install_repo_url: https://charts.bitnami.com/bitnami
    helm_install_name: nginx-server
    helm_install_release_namespace: nginx-server
    helm_install_create_namespace: true
    helm_install_chart_ref: bitnami/nginx
    helm_install_release_values:
      ingress:
        hostname: http.kube.devinforyou.com

  roles:
    - role: helm_install