- name: Ensure chart is installed
  hosts: all
  become: false
  gather_facts: false
  vars:
    helm_install_release_values: "{{ (helm_install_release_values_yaml | length > 0) | ternary((helm_install_release_values_yaml | from_yaml), omit)}}"

  roles:
    - role: helm_install