- name: Ensure Namespaces are at desired state
  hosts: all
  become: false
  gather_facts: false
  vars:
    kubernetes_namespaces_present:
      - name: "{{ namespace_present_name }}"
        labels: "{{ namespace_present_labels | from_yaml }}"

    kubernetes_namespaces_absent:
      - name: "{{ namespace_absent_name }}"

  roles:
     - role: kubernetes_namespace