---
- name: Enable cgroups via kernel commandline if not already enabled
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: reboot

- name: Ensure kernel modules are present
  ansible.builtin.package:
    name: linux-modules-extra-raspi
    state: present
  notify: reboot
